export const DEFAULT_SITE_SETTINGS = {
  id: 1,
  site_title: "Perpisahan Kelas 6 2026 SDN WANASARI 15",
  logo_url: "",
  dashboard_badge: "Album Kenangan 2026",
  dashboard_title: "Selamat datang di ruang kenangan perpisahan kelas 6.",
  dashboard_description:
    "Setiap foto dan video di sini menyimpan cerita tentang kebersamaan, tawa, dan langkah baru keluarga besar SDN Wanasari 15. Mari melihat kembali momen indah yang akan selalu menjadi bagian dari perjalanan kita.",
  photo_badge: "Galeri Foto",
  photo_title: "Kenangan dalam setiap bingkai",
  photo_description: "Temukan dokumentasi perpisahan kelas 6 dari berbagai sudut pengambilan.",
  video_badge: "Galeri Video",
  video_title: "Putar kembali momen terbaik",
  video_description: "Saksikan kembali suasana perpisahan kelas 6 SDN Wanasari 15 dalam bentuk video.",
  youtube_badge: "Video YouTube",
  youtube_title: "Galeri YouTube",
  youtube_description: "Kumpulan highlight acara kelulusan dan tasyakuran kelas 6 SDN Wanasari 15 pada 02 Juni 2026.",
  tiktok_badge: "Galeri TikTok",
  tiktok_title: "Video singkat, kenangan yang melekat",
  tiktok_description: "Kumpulan video TikTok perpisahan kelas 6 yang ditambahkan langsung melalui dashboard admin.",
  about_badge: "Tentang Developer",
  about_title: "Orang di balik website ini",
  about_description: "Sebuah perkenalan singkat dari pengembang ruang kenangan digital SDN Wanasari 15.",
  school_name: "SDN Wanasari 15",
  school_website_url: "https://sdnwanasari15.blogspot.com/p/dewan-guru-sdn-wanasari-15.html",
  school_instagram_url: import.meta.env.VITE_SCHOOL_INSTAGRAM_URL || "https://www.instagram.com/sdnwanasari15/",
  school_tiktok_url: import.meta.env.VITE_SCHOOL_TIKTOK_URL || "https://www.tiktok.com/@sdnwanasari15",
  developer_name: "Irfan",
  developer_photo_url: import.meta.env.VITE_DEVELOPER_PHOTO_URL || "",
  developer_role: "Developer Website",
  developer_intro:
    "Halo, saya Irfan, developer di balik website dokumentasi perpisahan ini. Saya juga seorang mahasiswa di Universitas Bani Saleh Bekasi yang senang mengembangkan pengalaman digital agar momen berharga dapat disimpan, ditemukan, dan dikenang dengan lebih mudah.",
  developer_university: "Universitas Bani Saleh Bekasi",
  developer_instagram_url: import.meta.env.VITE_DEVELOPER_INSTAGRAM_URL || "https://www.instagram.com/",
  developer_tiktok_url: import.meta.env.VITE_DEVELOPER_TIKTOK_URL || "https://www.tiktok.com/",
  developer_facebook_url: import.meta.env.VITE_DEVELOPER_FACEBOOK_URL || "https://www.facebook.com/",
};
